services:
  - type: web
    name: shadow-shop-backend
    env: python
    plan: free
    branch: main
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "false"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
  - type: worker
    name: shadow-shop-celery
    env: python
    plan: free
    branch: main
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config worker --loglevel=info
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "false"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
