# Generated by Django 5.0.6 on 2026-06-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconfig',
            name='bot_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
