# Generated by Django 5.0.6 on 2026-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationlog_reference_and_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconfig',
            name='new_order_payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
