# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_telegramconfig_new_order_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconfig',
            name='notify_contact_sales_copy',
            field=models.BooleanField(default=True),
        ),
    ]
