# Generated by Django 5.0.6 on 2026-09-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_telegramconfig_notify_contact_sales_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconfig',
            name='notify_staff_login',
            field=models.BooleanField(default=True),
        ),
    ]
