# Generated by Django 5.0.6 on 2026-07-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_contact_sales_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(choices=[('phnom_penh', 'Phnom Penh'), ('banteay_meanchey', 'Banteay Meanchey'), ('battambang', 'Battambang'), ('kampong_cham', 'Kampong Cham'), ('kampong_chhnang', 'Kampong Chhnang'), ('kampong_speu', 'Kampong Speu'), ('kampong_thom', 'Kampong Thom'), ('kampot', 'Kampot'), ('kandal', 'Kandal'), ('kep', 'Kep'), ('koh_kong', 'Koh Kong'), ('kratie', 'Kratie'), ('mondulkiri', 'Mondulkiri'), ('oddar_meanchey', 'Oddar Meanchey'), ('pailin', 'Pailin'), ('preah_sihanouk', 'Preah Sihanouk'), ('preah_vihear', 'Preah Vihear'), ('prey_veng', 'Prey Veng'), ('pursat', 'Pursat'), ('ratanakiri', 'Ratanakiri'), ('siem_reap', 'Siem Reap'), ('stung_treng', 'Stung Treng'), ('svay_rieng', 'Svay Rieng'), ('takeo', 'Takeo'), ('tboung_khmum', 'Tboung Khmum'), ('other', 'Other')], default='phnom_penh', max_length=50),
        ),
    ]
