# Generated by Django 5.0.6 on 2026-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_add_confirmed_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardsettings',
            name='birthday_bonus',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='daily_checkin_bonus',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='referral_bonus',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='review_bonus',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
