# Generated by Django 5.0.6 on 2026-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryByConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('telegram_group', models.CharField(blank=True, help_text='Telegram chat ID', max_length=100)),
                ('telegram_topic', models.IntegerField(blank=True, help_text='Telegram topic/thread ID', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_by_config',
                'ordering': ['name'],
            },
        ),
    ]
