# Generated by Django 5.0.6 on 2026-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=80, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=80)),
                ('telegram_user_id', models.CharField(blank=True, max_length=80)),
                ('telegram_username', models.CharField(blank=True, max_length=150)),
                ('otp_code', models.CharField(blank=True, max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telegram_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
