# Generated by Django 5.0.6 on 2026-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telegram_auth_date_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Shadow Shop', max_length=200)),
                ('store_phone', models.CharField(blank=True, max_length=50)),
                ('store_address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timezone', models.CharField(default='Asia/Phnom_Penh', max_length=50)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
    ]
