# Generated by Django 5.0.6 on 2026-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sitesettings_print_qr_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('products', 'Products'), ('inventory', 'Inventory'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'Users'), ('settings', 'Settings'), ('print', 'Print'), ('scanner', 'Scanner'), ('storefront', 'Customer Storefront')], max_length=50),
        ),
    ]
