# Generated by Django 5.0.6 on 2026-07-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_menu_submenu_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingregistration',
            new_name='pending_reg_email_7ef952_idx',
            old_name='pending_reg_email_dafd83_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingregistration',
            new_name='pending_reg_email_6135dd_idx',
            old_name='pending_reg_email_1d0e39_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
