# Generated by Django 5.0.6 on 2026-07-09 09:53

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_backfill_point_expiry'),
        ('payments', '0002_abapayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abapayment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aba_payment', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='bakongpayment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bakong_payment', to='orders.order'),
        ),
        migrations.CreateModel(
            name='PendingCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.payments.models.generate_pending_checkout_reference, max_length=20, unique=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('checkout_data', models.JSONField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_checkout', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_checkouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='abapayment',
            name='pending_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aba_payments', to='payments.pendingcheckout'),
        ),
        migrations.AddField(
            model_name='bakongpayment',
            name='pending_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bakong_payments', to='payments.pendingcheckout'),
        ),
    ]
