# Generated by Django 5.0.6 on 2026-06-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LuckyBox',
        ),
    ]
